### PR TITLE
Corrected import statement

### PR DESCRIPTION
**Pull request by TariniHardikar**

### CODE REVIEW

**Comment by babbush** [comment]
Hi Tarini,

Did you sign the CLA?

**Comment by TariniHardikar** [comment]
Hi Ryan,

Unfortunately, I'll have to wait for Dartmouth Technology to get back to me before I can sign it. I'll do my best to have it done soon.

**Comment by babbush** [comment]
Okay. You may also want to talk to @kanavsetia since he has signed it and works at Dartmouth. Note that you should sign the individual CLA.

**Comment by TariniHardikar** [comment]
I signed it!

**Pull request merged**
